[theme]
base = "light"
primaryColor = "#2864DC"
backgroundColor = "#F8FAFD"
secondaryBackgroundColor = "#EEF3FA"
textColor = "#0B1739"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 20
fileWatcherType = "none"

[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false
